### ISSUE TITLE
Can not run directly without instalation (as described in README)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yendo/gphotoframe#29]
```
What steps will reproduce the problem?
1. Extract the gphotoframe-0.4.1 directory (in my case in ~/Desktop)
2. cd gphotoframe-0.4.1
3. ./gphotoframe

What is the expected output? What do you see instead?
I expect it to run. I get
/var/lib/python-support/python2.6/gdata/tlslite/utils/cryptomath.py:9:
DeprecationWarning: the sha module is deprecated; use the hashlib module
instead
  import sha
Can't import flickr plugin: No module named simplejson.
Can't import tumblr plugin: No module named simplejson.
Can't import rss plugin: No module named feedparser.

(gphotoframe:15310): libglade-WARNING **: could not find glade file
'/usr/share/gphotoframe/gphotoframe.glade'
Traceback (most recent call last):
  File "./gphotoframe", line 22, in <module>
    PhotoListStore()
  File "/home/ravn/Desktop/gphotoframe-0.4.1/lib/photoliststore.py", line
23, in __init__
    self.photoframe = PhotoFrameFactory().create(self)
  File "/home/ravn/Desktop/gphotoframe-0.4.1/lib/photoframe.py", line 23,
in create
    photoframe = PhotoFrame(photolist)
  File "/home/ravn/Desktop/gphotoframe-0.4.1/lib/photoframe.py", line 33,
in __init__
    gui = gtk.glade.XML(constants.GLADE_FILE)
RuntimeError: could not create GladeXML object


What version of the product are you using? On what operating system?
Ubunutu 9.04

Please provide any additional information below.
-
```

Original issue reported on code.google.com by `Robert.R...@gmail.com` on 17 Aug 2009 at 6:35

**Comment by GoogleCodeExporter** [comment]
```
same here. Even with the install.

It seems that the default install is in /usr/local but gphotoframe searchfor 
files in
/usr/
```

Original comment by `nemoliv...@gmail.com` on 17 Aug 2009 at 8:05

**Comment by GoogleCodeExporter** [comment]
```
Installing with  
sudo python setup.py --prefix=/usr --force
solve the problem for the install (0.4.1)
```

Original comment by `nemoliv...@gmail.com` on 17 Aug 2009 at 1:40

**Comment by GoogleCodeExporter** [comment]
```
Installing does not work for me. The dependency of DistUtilsExtra is not met. It
should probably be bundled with the source.
```

Original comment by `Robert.R...@gmail.com` on 18 Aug 2009 at 5:55

**Comment by GoogleCodeExporter** [comment]
```
After adding the distutils-extra package in Ubuntu I don't get an error. But the
--prefix command is not recognised:
sudo python setup.py --prefix=/usr/local --force
[sudo] password for ravn: 
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --prefix not recognized
```

Original comment by `Robert.R...@gmail.com` on 18 Aug 2009 at 6:01

**Comment by GoogleCodeExporter** [comment]
```
Sorry, I forgot the « install » in the command line : 
sudo python setup.py install --prefix=/usr --force

```

Original comment by `nemoliv...@gmail.com` on 18 Aug 2009 at 7:40

**Comment by GoogleCodeExporter** [comment]
```
Now install works (installed to /usr/local), but the I get:
$ gphotoframe 
Traceback (most recent call last):
  File "/usr/local/bin/gphotoframe", line 19, in <module>
    from gphotoframe.photoliststore import PhotoListStore
ImportError: No module named gphotoframe.photoliststore
```

Original comment by `Robert.R...@gmail.com` on 18 Aug 2009 at 10:09

**Comment by GoogleCodeExporter** [comment]
```
I had this on my girlfriend computer. Same with svn. The infolder command
« ./gphotoframe » work. After several test of install in /usr and 
/usr/local I got it
to run (don’t understand).
```

Original comment by `nemoliv...@gmail.com` on 18 Aug 2009 at 10:17

**Comment by GoogleCodeExporter** [comment]
```
Thanks for reporting.

The problem that gphotoframe is not able to 
run directly without instalation is fixed in r226.

The install prefix problem is other problem.
I added new issue #30.

```

Original comment by `yendo0206` on 18 Aug 2009 at 10:41
- Changed state: **Fixed**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yendo0206` on 18 Aug 2009 at 11:16
