### ISSUE TITLE
PyXGD v.0.16 has an indentation bug.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [yendo/gphotoframe#9]
```
What steps will reproduce the problem?

After setup and install. Gphotoframe fail to run.


What is the expected output? What do you see instead?

gphotoframe 
Traceback (most recent call last):
  File "/usr/bin/gphotoframe", line 19, in <module>
    from gphotoframe.photoliststore import PhotoListStore
  File "/usr/lib/python2.5/site-packages/gphotoframe/photoliststore.py",
line 5, in <module>
    from photoframe import PhotoFrame
  File "/usr/lib/python2.5/site-packages/gphotoframe/photoframe.py", line
9, in <module>
    from preferences import Preferences
  File "/usr/lib/python2.5/site-packages/gphotoframe/preferences.py", line
9, in <module>
    from utils.autostart import AutoStart
  File "/usr/lib/python2.5/site-packages/gphotoframe/utils/autostart.py",
line 3, in <module>
    from xdg.DesktopEntry import *
  File "/usr/lib/python2.5/site-packages/xdg/DesktopEntry.py", line 184
    self.errors.append("Group may either have OnlyShowIn or NotShowIn, but
not both")
       ^
IndentationError: expected an indented block


What version of the product are you using? On what operating system?


Gphotoframe-0.2. I'm on Slackware 12.2 with additional dependencies
installed ( Pyxdg, Twisted...)


Please provide any additional information below.


```

Original issue reported on code.google.com by `gohan...@gmail.com` on 17 May 2009 at 5:33

**Comment by GoogleCodeExporter** [comment]
```
> File "/usr/lib/python2.5/site-packages/xdg/DesktopEntry.py", line 184
>     self.errors.append("Group may either have OnlyShowIn or NotShowIn, but 
not both")
>        ^
> IndentationError: expected an indented block

It seems that this bug is in the PyXDG module.
What version of the PyXDG module have you installed?
```

Original comment by `yendo0206` on 18 May 2009 at 5:59

**Comment by GoogleCodeExporter** [comment]
```
I have installed pyxdg-0.16.
```

Original comment by `gohan...@gmail.com` on 18 May 2009 at 6:26

**Comment by GoogleCodeExporter** [comment]
```
I confirm that python-xdg v.1.6 has an indentation bug.
Please install python-xdg v.1.7.
```

Original comment by `yendo0206` on 18 May 2009 at 6:41
- Changed state: **Done**
- Added labels: **Type-Other**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
Oops,

> I confirm that python-xdg v.1.6 has an indentation bug.
> Please install python-xdg v.1.7.

PyXDG v.0.16 has an indentation bug.
Please install PyXDG v.0.17.

```

Original comment by `yendo0206` on 18 May 2009 at 6:46
- Changed title: **PyXGD v.0.16 has an indentation bug.**

**Comment by GoogleCodeExporter** [comment]
Original comment by `yendo0206` on 18 May 2009 at 6:47

**Comment by GoogleCodeExporter** [comment]
```
Thanks a lot after pyxdg upgrade. Gphotoframe run correctly!
```

Original comment by `gohan...@gmail.com` on 18 May 2009 at 6:48

**Comment by GoogleCodeExporter** [comment]
```
Thank you for your information.
Added a notice of a pyxdg bug to the project home page.
```

Original comment by `yendo0206` on 18 May 2009 at 6:57
